### ISSUE TITLE
新能源汽车的车牌号码需要适配

### ISSUE THREAD

**Issue by hebai001** [rztime/RZCarPlateNumberKeyboard#3]
新能源汽车的车牌号码需要适配,新能源汽车车牌增加了一位,例如:粤BF12345

**Comment by rztime** [comment]
车牌号位数可以自行设置7、8位甚至更多或更少，且可以设置校正输入值的有效性，或者你可以pod update，（RZCarPlateNoTextField改了一下名字，还请修改一下对应用到的地方）

如果有校验文本的错误，请反馈一下格式，或者在rz_regexPlateNoIfYouNeed自行设置校验格式（请参考原校验方式对比）。。谢谢
